### ISSUE TITLE
Pseudo element reveal

### ISSUE THREAD

**Issue by supertassu** [jlmakes/scrollreveal#388]
Hello! 

First, thanks for the amazing library. 
Anyway, my actual problem; I'm trying to reveal an `::after` pseudo element.

```html
(not full code)

<style>
p {
    display: inline-block;
    padding-bottom: 5px;
    position: relative;
}

p::after {
    content: "";
    position: absolute;
    width: 25%;
    height: 1px;
    bottom: 0;
    left: 0%;
    border-bottom: 3px solid darkgray;

}
</style>

<p>I'm underlined!</p>

<script src="js/scrollreveal.min.js"></script>
<script>
    window.sr = ScrollReveal();
    sr.reveal("p::after");
</script>

```

Yeah. That doesn't work.

 - Microsoft Windows [Version 10.0.15063]
 - Google Chrome [Version 61.0.3163.100 (64-bit)] 
 - Fully valid HTML

Thanks!

**Comment by jlmakes** [comment]
Hi Tassu,

Pseudo elements are not accessible with JavaScript, as they are not really a part of the DOM; try accessing the element without ScrollReveal:

```js
document.querySelector('p::after') // null
```

This is why using ScrollReveal directly on pseudo elements will not work.

**Comment by supertassu** [comment]
Oh. Great. Is there any workaround?

**Comment by jlmakes** [comment]
Well, you could think of ScrollReveal as two main features:

1. Detects when elements are visible
2. Generates CSS to apply to elements that are visible

We’ve already seen how `p::after` doesn’t work as a selector, but even if find a different way to get ahold of the right element, we still can't apply the generated styles to the pseudo element.

**To be honest, ScrollReveal is not really a good fit here.**

you’ll need to create your own CSS transitions, something like:

```css
p {
    display: inline-block;
    padding-bottom: 5px;
    position: relative;
}

p::after {
    content: "";
    position: absolute;
    width: 25%;
    height: 1px;
    left: 0%;
    border-bottom: 3px solid darkgray;

    bottom: 100px;
    transition: 0.3s bottom;
}

p.visible::after {
    bottom: 0;
}
```

And then you need to apply `.visible` to the `<p>` when it's visible.
