### ISSUE TITLE
Overwrite transform

### ISSUE THREAD

**Issue by rosshulford** [jlmakes/scrollreveal#424]
I position a div centrally with:

```css
{
  top: 50%;
  left: 50%;
  transform: translate(-50%, 50%);
}
```

When I add the following reveal:

```js
var fadeInUp = {
  origin: 'bottom',
  distance: '200px',
  duration: 1000,
   scale: 1,
   easing: 'ease-in-out',
   viewFactor: 0.6,
}
```

It overwrites the x-transform pushing it to the right, the div properties are

```css
{
    visibility: visible;
    -webkit-transform: translateY(0) scale(1);
    opacity: 1;
    transform: translateY(0) scale(1);
    opacity: 1;
    -webkit-transition: -webkit-transform 1s ease-in-out 0s, opacity 1s ease-in-out 0s;
    transition: transform 1s ease-in-out 0s, opacity 1s ease-in-out 0s;
}
```

Can this be fixed?  I am using v3.4.0
