### ISSUE TITLE
SR element in a wrapper div with overflow auto isn't firing when it comes into the view port

### ISSUE THREAD

**Issue by devanflaherty** [jlmakes/scrollreveal#445]
MacOs
Chrome 67
Scroll Reveal 3.4

I have used Scroll Reveal for 2 years and have loved it!

I recently attempted to utilize some pure css parallax, in order to do so I had to modify my pages `.wrapper` to look like so.

``` scss
.wrapper {
   perspective: 1px;
   height: 100vh;
   overflow-x: hidden;
   overflow-y: auto;
}
```

Then on a div I want to parallax I add a little something like this:
```scss
.parralaxed-thing {
   transform: translateZ(-1px) scale(2);
}
```

A strange thing is happening though where my scroll-reveal elements are never firing, it's as if they aren't aware they become visible in the view port.

I thought it had something to do with the `perspective: 1px` but it seems that it is actually related to `.wrapper` being set to overflow.

Any ideas on how I can utilize scroll reveal and having the parent container set to `height: 100vh; overflow-y: auto;`?

Thanks!
