### ISSUE TITLE
overflow-x: hidden bug

### ISSUE THREAD

**Issue by mkuba2006** [jlmakes/scrollreveal#571]
# does anyone know how to fix this

```css
body {
    margin: 0;
    padding: 0;
    overflow-x: hidden; <--- because of that ScrollReveal animation doesn't work
}
```
