### ISSUE TITLE
How to disable animations on smaller screens?

### ISSUE THREAD

**Issue by gr2m** [jlmakes/scrollreveal#72]
I hope I could just add this CSS

``` css
@media (max-width: 480px) {

  /* disable scroll reveal */
  [data-sr] {
    -webkit-tranform: none !important;
    transform: none !important;
  }
}
```

but it didn't do the trick (in latest Chrome). Do you have a suggestion?
